version: '2'
services:
    apache:
        image: apache
        container_name: apache
        ports:
            - '8080:80'
            - '8443:443'
        volumes:
            - "./:/var/www/html"
